name: npm-publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i --package-lock-only
        working-directory: ./node-red-contrib-c8y-client
      - run: npm ci
        working-directory: ./node-red-contrib-c8y-client
      - run: npm publish --provenance --access public
        working-directory: ./node-red-contrib-c8y-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}